---
name: Build and Publish Talos Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TALOS_VERSION: "v1.8.3"
  EXTENSION01: "ghcr.io/siderolabs/iscsi-tools:v0.1.6"
  EXTENSION02: "ghcr.io/siderolabs/util-linux-tools:2.40.1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: echo "Building project"

      - name: Create Talos image with extensions
        run: |
          docker run --rm -t \
            -v ${{ github.workspace }}/_out:/out \
            ghcr.io/nberlee/imager:${{ env.TALOS_VERSION }} installer \
            --arch arm64 \
            --platform metal \
            --overlay-name turingrk1 \
            --overlay-image ghcr.io/nberlee/sbc-turingrk1:${{ env.TALOS_VERSION }} \
            --base-installer-image ghcr.io/nberlee/installer:${{ env.TALOS_VERSION }}-rk3588 \
            --system-extension-image ghcr.io/nberlee/rk3588:${{ env.TALOS_VERSION }} \
            --system-extension-image ${{ env.EXTENSION01 }} \
            --system-extension-image ${{ env.EXTENSION02 }}

      - name: Upload Talos image
        uses: actions/upload-artifact@v3
        with:
          name: talos-image
          path: ${{ github.workspace }}/_out/installer-arm64.tar

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install crane
        uses: iarekylew00t/crane-installer@v3

      - name: Download Talos image
        uses: actions/download-artifact@v3
        with:
          name: talos-image
          path: ${{ github.workspace }}/_out

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Talos image to GitHub Container Registry
        run: |
          crane auth login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          crane push ${{ github.workspace }}/_out/installer-arm64.tar ghcr.io/cloud-native-engineering/sem04_setup/installer-arm64:${{ env.TALOS_VERSION }}
